# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89860983cf532b70fa32e518f1133c345b0dc4b9041b90190e2d4ecfb4bb3b03cb0b248923c8be3f71bf1ae44cc5857e0da2e41e5c26215ffd22633834895a90

test:
  secret_key_base: 78bff82eba3c58b62c2660f6479fa11faafdf1df53a658605b7713a3ed4aad78a646afdbef5a3aed8b074246c693a7c71d3810874878628521d3a053dc285cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
